=== estruyf/blog-content/static/dev/speaking.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://www.eliostruyf.com/dev/speaking.schema.json",
  "title": "Speaking schema",
  "description": "Schema for the speaking engagements",
  "lastModified": "2024-06-06",
  "type": "object",
  "properties": {
    "title": {
      "type": "string",
      "description": "Title of the session"
    },
    "description": {
      "type": "string",
      "description": "Abstract of the session"
    },
    "startDate": {
      "type": "string",
      "format": "date",
      "description": "Date of the speaking engagement (YYYY-MM-DD)"
    },
    "endDate": {
      "type": "string",
      "format": "date",
      "description": "End date of the speaking engagement (YYYY-MM-DD)"
    },
    "location": {
      "type": "string",
      "description": "Location of the speaking engagement"
    },
    "event": {
      "type": "object",
      "description": "Event details",
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of the event"
        },
        "link": {
          "type": "string",
          "format": "uri",
          "description": "URL of the event"
        }
      }
    },
    "links": {
      "type": "array",
      "description": "Links to the session",
      "items": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "description": "Title of the link"
          },
          "link": {
            "type": "string",
            "format": "uri",
            "description": "URL of the link"
          }
        }
      }
    },
    "reporting": {
      "type": "object",
      "description": "Reporting details",
      "properties": {
        "gde": {
          "type": "boolean",
          "description": "Is added to Google Developer Expert profile?"
        },
        "mvp": {
          "type": "boolean",
          "description": "Is added to Microsoft MVP profile?"
        },
        "github": {
          "type": "boolean",
          "description": "Is added to GitHub Star profile?"
        }
      }
    }
  }
}

=== estruyf/blog-content/data/speaking.json
[{
  "$schema": "https://www.eliostruyf.com/dev/speaking.schema.json",
  "title": "Ensure quality in Power Apps by integrating automated testing with Playwright",
  "description": "Low-code/no-code platforms like Power Apps have transformed how we build business applications, but they require robust testing like any other software. This session will explore how to use Playwright to automate testing for Power Apps solutions, ensuring reliability even in rapidly evolving environments. We will demonstrate how to create end-to-end tests for common Power Apps scenarios, mock connectors, and prepare for deployment. You will also learn best practices for building practical tests to catch bugs and regressions early. Expect to see some real code! By the end of this session, you will understand how to leverage Playwright to enhance the quality of your Power Apps solutions.",
  "startDate": "2025-02-22",
  "endDate": "2025-02-22",
  "location": "Edegem (BE)",
  "event": {
    "name": "Global Power Platform Bootcamp 2025 - Belgium Edition",
    "link": "https://www.powerplatformbootcamp.com/2025/location-detail/?id=b708fc52-8d96-ef11-95f5-6045bd5f73bf&city=Belgian+PowerAddicts"
  },
  "links": [{
    "title": "Link to the event",
    "link": "https://www.powerplatformbootcamp.com/2025/location-detail/?id=b708fc52-8d96-ef11-95f5-6045bd5f73bf&city=Belgian+PowerAddicts"
  }],
  "reporting": {
    "gde": false,
    "mvp": false,
    "github": false
  }
}, {
    "$schema": "https://www.eliostruyf.com/dev/speaking.schema.json",
    "title": " Integrate Playwright tests for Power Apps into your DevOps process",
    "description": "Tired of Power Platform solutions that feel like being held together by duct tape and bubble gum? You're not alone. In this session, Luise and Elio will discuss why proper testing is often overlooked in Power Apps development and how we can change that game. We'll introduce you to Playwright, your new best friend for automated testing, and show you why it's a perfect match for Power Apps. We'll cover the essentials of making your apps test-friendly and walk you through some common tests to get you started. But we won't stop there. We'll show you how to take your testing to the next level by automating the process and seamlessly integrating it into your development pipeline. By the end of this session, you'll have a clear roadmap for releasing rock-solid Power Apps that'll make your users (and your sanity) thank you.",
    "startDate": "2025-05-26",
    "endDate": "2025-05-28",
    "location": "Dusseldorf (DE)",
    "event": {
      "name": "European BizApps Summit 2025",
      "link": "https://bizappssummit.eu/"
    },
    "links": [{
      "title": "Link to the event",
      "link": "https://bizappssummit.eu/"
    }],
    "reporting": {
      "gde": false,
      "mvp": false,
      "github": true
    }
  }, {
    "$schema": "https://www.eliostruyf.com/dev/speaking.schema.json",
    "title": "Test Automation with GitHub Actions and Playwright for Microsoft 365 solutions",
    "description": "GitHub Actions is a powerful tool for creating and running CI/CD pipelines. Playwright is a modern tool for end-to-end testing. In this session, you will learn how to combine these two tools to automate your testing process and improve the quality of your Microsoft 365 solutions. You will see how to set up GitHub Actions for running Playwright tests, handle test results and notifications, and follow best practices for test automation. By the end of this session, you will have the skills and confidence to implement test automation in your projects with GitHub Actions and Playwright.",
    "startDate": "2025-05-26",
    "endDate": "2025-05-28",
    "location": "Dusseldorf (DE)",
    "event": {
      "name": "European Collaboration Summit",
      "link": "https://collabsummit.eu/"
    },
    "links": [{
      "title": "Link to the event",
      "link": "https://collabsummit.eu/"
    }],
    "reporting": {
      "gde": false,
      "mvp": false,
      "github": true
    }
  }, {
    "$schema": "https://www.eliostruyf.com/dev/speaking.schema.json",
    "title": "Test Automation with GitHub Actions and Playwright for Microsoft 365 solutions",
    "description": "GitHub Actions is a powerful tool for creating and running CI/CD pipelines. Playwright is a modern tool for end-to-end testing. In this session, you will learn how to combine these two tools to automate your testing process and improve the quality of your Microsoft 365 solutions. You will see how to set up GitHub Actions for running Playwright tests, handle test results and notifications, and follow best practices for test automation. By the end of this session, you will have the skills and confidence to implement test automation in your projects with GitHub Actions and Playwright.",
    "startDate": "2024-10-19",
    "endDate": "2024-10-19",
    "location": "BluePoint Brussels",
    "event": {
      "name": "CollabDays BE",
      "link": "https://www.collabdays.org/2024-belgium/"
    },
    "links": [{
      "title": "Link to the event",
      "link": "https://www.collabdays.org/2024-belgium/"
    }],
    "reporting": {
      "gde": true,
      "mvp": false,
      "github": true
    }
  }, {
    "$schema": "https://www.eliostruyf.com/dev/speaking.schema.json",
    "title": "From Code to Cloud: Automated Deployments with GitHub Actions",
    "description": "Let us dive into the world of GitHub Actions, an instrumental component in modern Continuous Integration and Continuous Deployment (CI/CD) practices. In this session, we'll explore how to harness GitHub Actions to streamline your deployment workflows, making the process of moving from code commits to live deployments seamless and efficient. We'll cover how to use variables, secrets, environment approvals, local testing, and more. If you want to automate your deployments, this session is for you!",
    "startDate": "2024-11-20",
    "endDate": "2024-11-20",
    "location": "HOGENT Campus Schoonmeersen",
    "event": {
      "name": "VisugXL 2024",
      "link": "https://www.visug.be"
    },
    "links": [{
      "title": "Link to the event",
      "link": "https://www.visug.be/Events/95"
    }],
    "reporting": {
      "gde": false,
      "mvp": false,
      "github": true
    }
  }, {
    "$schema": "https://www.eliostruyf.com/dev/speaking.schema.json",
    "title": "MVP sharing session: get insights from Microsoft MVPs to become the next MVP",
    "description": "Community event from PowerAddicts",
    "startDate": "2024-09-04",
    "endDate": "2024-09-04",
    "location": "Kontich (BE)",
    "event": {
      "name": "PowerAddicts",
      "link": "https://www.poweraddicts.be"
    },
    "links": [{
      "title": "Link to the event",
      "link": "https://www.poweraddicts.be/summer-event-powerbbq-04-sept-2024/"
    }],
    "reporting": {
      "gde": false,
      "mvp": false,
      "github": true
    }
  },
  {
    "$schema": "https://www.eliostruyf.com/dev/speaking.schema.json",
    "title": "Test Automation with GitHub Actions and Playwright for Microsoft 365 solutions",
    "description": "GitHub Actions is a powerful tool for creating and running CI/CD pipelines. Playwright is a modern tool for end-to-end testing. In this session, you will learn how to combine these two tools to automate your testing process and improve the quality of your Microsoft 365 solutions. You will see how to set up GitHub Actions for running Playwright tests, handle test results and notifications, and follow best practices for test automation. By the end of this session, you will have the skills and confidence to implement test automation in your projects with GitHub Actions and Playwright.",
    "startDate": "2024-12-02",
    "endDate": "2024-12-05",
    "location": "Stockholm (SE)",
    "event": {
      "name": "ESPC",
      "link": "https://www.sharepointeurope.com/"
    },
    "links": [{
      "title": "Link to the event",
      "link": "https://www.sharepointeurope.com/"
    }],
    "reporting": {
      "gde": true,
      "mvp": true,
      "github": true
    }
  },
  {
    "title": "Automated Testing for Microsoft 365 with Playwright",
    "description": "In this session, we will explore how to use Playwright to automate testing of Microsoft 365 applications. We will focus on how Playwright can be used to create end-to-end tests that verify the behavior of Microsoft 365 applications for Microsoft Teams, and SharePoint. We will discuss how Playwright can be integrated into a continuous integration and deployment (CI/CD) pipeline, and how it can be used to catch bugs and regressions before they reach production. Additionally, we will provide tips and best practices for creating effective tests that cover common scenarios in Microsoft 365 applications. By the end of this session, attendees will have a deeper understanding of how to use Playwright to improve the quality of their Microsoft 365 applications.",
    "startDate": "2024-06-01",
    "endDate": "2024-06-01",
    "location": "Vianen (NL)",
    "event": {
      "name": "CollabDays NL",
      "link": "https://www.collabdays.org/2024-nl/"
    },
    "links": [{
      "title": "Link to the event",
      "link": "https://www.collabdays.org/2024-nl/"
    }],
    "reporting": {
      "gde": true,
      "mvp": true,
      "github": true
    }
  },
  {
    "title": "From Code to Cloud: Automated Deployments with GitHub Actions",
    "description": "Let us dive into the world of GitHub Actions, an instrumental component in modern Continuous Integration and Continuous Deployment (CI/CD) practices. In this session, we'll explore how to harness GitHub Actions to streamline your deployment workflows, making the process of moving from code commits to live deployments seamless and efficient. We'll cover how to use variables, secrets, environment approvals, and more. If you want to automate your deployments, this session is for you!",
    "startDate": "2024-05-29",
